{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoError","stack":"MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","level":"warn","timestamp":"2017-09-27T14:58:14.921Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoError","stack":"MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","level":"warn","timestamp":"2017-09-27T14:58:14.923Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:42.014Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:42.017Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:42.019Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:42.019Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:43.071Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:43.071Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:43.072Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:43.073Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:44.590Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:44.590Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:44.592Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:44.593Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:45.830Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:45.831Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:45.832Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:45.833Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:45.839Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:45.839Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:47.348Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:47.349Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:47.351Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:47.352Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:47.353Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:47.354Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:48.576Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:48.577Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:48.578Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:48.579Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:48.581Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:48.582Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:48.584Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:48.584Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:48.586Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:48.586Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:49.934Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:49.934Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:49.935Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:49.936Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:49.936Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:49.937Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:49.938Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:49.938Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:49.939Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:49.940Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:51.103Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:51.104Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:51.106Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:51.107Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:51.108Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:51.108Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:51.110Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:51.110Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:52.483Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:52.484Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:52.484Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:52.485Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:52.485Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:52.486Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:52.487Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:52.487Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:52.488Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:52.489Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:54.071Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:54.072Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:54.073Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:54.075Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:54.076Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:54.077Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T14:59:56.398Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T14:59:56.399Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:32.374Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:32.375Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:33.455Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:33.455Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:35.110Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:35.110Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:36.490Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:36.490Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:36.491Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:36.492Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:36.492Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:36.493Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:36.493Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:36.494Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:37.515Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:37.516Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:37.516Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:37.517Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:37.517Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:37.518Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:37.518Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:37.519Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:37.520Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:37.520Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:37.521Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:37.521Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:37.522Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:37.522Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:38.530Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:38.531Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:38.533Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:38.536Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:38.536Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:38.537Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:38.538Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:38.538Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:38.540Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:38.540Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:38.541Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:38.541Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:38.543Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:38.544Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:39.555Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:39.556Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:39.556Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:39.557Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:39.557Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:39.558Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:40.594Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:40.594Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:42.026Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:42.027Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-09-27T15:00:43.762Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (C:\\Users\\huas\\AppData\\Roaming\\npm\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-09-27T15:00:43.762Z"}
